# Generated by Django 4.2 on 2026-03-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('source_type', models.CharField(choices=[('upload', '本地上传'), ('url', 'URL下载')], max_length=20)),
                ('source_path', models.CharField(max_length=500)),
                ('target_directory', models.CharField(max_length=500)),
                ('gray_ratio', models.FloatField(default=0.1)),
                ('current_gray_ratio', models.FloatField(default=0.1)),
                ('status', models.CharField(choices=[('pending', '待发布'), ('graying', '灰度中'), ('paused', '暂停'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=50)),
                ('current_version', models.CharField(default='0.0.0', max_length=50)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_records', to='core.node')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deploytask')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='core.nodegroup'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='groups',
            field=models.ManyToManyField(related_name='tasks', to='core.nodegroup'),
        ),
        migrations.CreateModel(
            name='TaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to='core.node')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to='core.deploytask')),
            ],
            options={
                'unique_together': {('task', 'node')},
            },
        ),
    ]
