# Generated by Django 4.2 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deploymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='is_executable',
            field=models.BooleanField(default=False),
        ),
    ]
