# Generated by Django 4.2 on 2026-03-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deploytask_is_executable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='target_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
