# Generated by Django 4.2 on 2026-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deploytask_target_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='post_deploy_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
